"""
pairbot.py  --  Pair-trading backtester + dashboard engine
===========================================================
You normally do NOT edit this file. Edit 'pairs.json' to change pairs/thresholds,
then run 'run.py'. This file does the actual work in clearly labeled sections:

  1) CONFIG      - read pairs.json
  2) DATA        - download free price history from Yahoo Finance
  3) STRATEGY    - turn prices into a spread + z-score + trade signals
  4) BACKTEST    - simulate the strategy and record every completed trade
  5) WATCHLIST   - compute the CURRENT signal for the pairs you're watching
  6) DASHBOARD   - build a single self-contained dashboard.html
"""

import json
import os
import datetime as dt

import numpy as np
import pandas as pd
import yfinance as yf

import plotly.graph_objects as go
from plotly.subplots import make_subplots

HERE = os.path.dirname(os.path.abspath(__file__))
DATA_DIR = os.path.join(HERE, "data")
os.makedirs(DATA_DIR, exist_ok=True)


# ---------------------------------------------------------------------------
# 1) CONFIG
# ---------------------------------------------------------------------------
def load_config():
    """Read pairs.json and fill in each pair/watchlist item with the defaults."""
    with open(os.path.join(HERE, "pairs.json")) as f:
        cfg = json.load(f)
    defaults = cfg.get("defaults", {})

    def fill(item):
        merged = dict(defaults)
        merged.update(item)
        merged["a"] = merged["a"].upper().strip()
        merged["b"] = merged["b"].upper().strip()
        merged["name"] = f'{merged["a"]}/{merged["b"]}'
        return merged

    cfg["pairs"] = [fill(p) for p in cfg.get("pairs", [])]
    cfg["watchlist"] = [fill(p) for p in cfg.get("watchlist", [])]
    cfg.setdefault("history_period", "2y")
    return cfg


# ---------------------------------------------------------------------------
# 2) DATA
# ---------------------------------------------------------------------------
def fetch_prices(tickers, period="2y"):
    """Download adjusted daily closing prices for all tickers in one request."""
    tickers = sorted(set(tickers))
    data = yf.download(tickers, period=period, progress=False, auto_adjust=True)
    close = data["Close"]
    if isinstance(close, pd.Series):          # only one ticker came back
        close = close.to_frame()
    close = close.dropna(how="all").ffill()   # carry last price over missing days
    return close


# ---------------------------------------------------------------------------
# 3) STRATEGY
# ---------------------------------------------------------------------------
def compute_spread(close, pair):
    """
    Spread = ratio of the two prices (A / B).
    z-score = how many standard deviations today's ratio is from its recent average.
    A big positive z means A is unusually EXPENSIVE vs B (and vice-versa).
    """
    a, b = pair["a"], pair["b"]
    ratio = close[a] / close[b]
    mean = ratio.rolling(pair["lookback"]).mean()
    std = ratio.rolling(pair["lookback"]).std()
    z = (ratio - mean) / std
    return pd.DataFrame({"ratio": ratio, "mean": mean, "std": std, "z": z})


def _trade_pnl(mode, direction, entry_a, entry_b, exit_a, exit_b, capital):
    """
    Dollar P&L of a trade. `direction` is consistent across modes:
      +1 = A is the cheap side (we go long A; long_short also shorts B)
      -1 = B is the cheap side (we go long B; long_short also shorts A)
    """
    ret_a = exit_a / entry_a - 1.0
    ret_b = exit_b / entry_b - 1.0
    if mode == "long_only":
        # buy ONLY the cheap leg, no short position at all
        return capital * (ret_a if direction == +1 else ret_b)
    # classic market-neutral long/short
    if direction == +1:          # long A, short B
        return capital * (ret_a - ret_b)
    else:                        # short A, long B
        return capital * (ret_b - ret_a)


def _trade_cost(mode, capital, cost_bps):
    """
    Round-trip trading cost in dollars (bid/ask spread + slippage), charged on
    BOTH entry and exit, for each leg we actually trade. Robinhood is commission
    -free, but you still cross the spread — so this keeps P&L honest.
      long_only  = 1 leg traded;  long_short = 2 legs traded.
    """
    legs = 1 if mode == "long_only" else 2
    per_side = capital * (cost_bps / 10000.0)
    return legs * per_side * 2      # *2 = entry + exit


def _direction_label(mode, direction, a, b):
    if mode == "long_only":
        return f"LONG {a} (cheap leg)" if direction == +1 else f"LONG {b} (cheap leg)"
    return (f"LONG spread (long {a} / short {b})" if direction == +1
            else f"SHORT spread (short {a} / long {b})")


# ---------------------------------------------------------------------------
# 4) BACKTEST
# ---------------------------------------------------------------------------
def backtest_pair(close, pair):
    """
    Walk forward day by day. Open a trade when |z| crosses entry_z,
    close it when z reverts past exit_z (or hits the stop_z loss guard).
    Returns: (list of trade dicts, daily cumulative-P&L Series).
    """
    a, b = pair["a"], pair["b"]
    sp = compute_spread(close, pair)
    pa = close[a].reindex(sp.index)
    pb = close[b].reindex(sp.index)

    entry_z = pair["entry_z"]
    exit_z = pair["exit_z"]
    stop_z = pair.get("stop_z")
    max_days = pair.get("max_days")          # optional time stop (calendar days)
    capital = pair["capital_per_leg"]
    mode = pair.get("mode", "long_short")
    cost_bps = pair.get("cost_bps", 0)
    round_trip_cost = _trade_cost(mode, capital, cost_bps)

    position = 0          # 0 flat, +1 long spread, -1 short spread
    e_date = e_a = e_b = e_z = None
    realized = 0.0
    trades = []
    daily = []
    n = len(sp)

    for i in range(n):
        date = sp.index[i]
        z = sp["z"].iat[i]
        a_px = pa.iat[i]
        b_px = pb.iat[i]

        if np.isnan(z) or np.isnan(a_px) or np.isnan(b_px):
            daily.append((date, realized))
            continue

        # We DECIDE on today's z but FILL at the next session's price — you can't
        # act on a close until the following day. This removes same-bar look-ahead.
        has_next = i + 1 < n
        fa = pa.iat[i + 1] if has_next else np.nan
        fb = pb.iat[i + 1] if has_next else np.nan
        f_date = sp.index[i + 1] if has_next else date
        can_fill = has_next and not (np.isnan(fa) or np.isnan(fb))

        if position == 0:
            if can_fill and z >= entry_z:
                position, e_date, e_a, e_b, e_z = -1, f_date, fa, fb, z
            elif can_fill and z <= -entry_z:
                position, e_date, e_a, e_b, e_z = +1, f_date, fa, fb, z
        else:
            held = (date - e_date).days
            hit_target = abs(z) <= exit_z
            hit_stop = stop_z is not None and abs(z) >= stop_z
            hit_time = max_days is not None and held >= max_days
            if (hit_target or hit_stop or hit_time) and can_fill:
                pnl = _trade_pnl(mode, position, e_a, e_b, fa, fb, capital)
                pnl -= round_trip_cost          # charge spread/slippage both sides
                realized += pnl
                if hit_stop and not hit_target:
                    reason = "stop-loss"
                elif hit_target:
                    reason = "reverted"
                else:
                    reason = "time-stop"
                trades.append({
                    "pair": pair["name"],
                    "direction": _direction_label(mode, position, a, b),
                    "entry_date": e_date.date().isoformat(),
                    "exit_date": f_date.date().isoformat(),
                    "days_held": (f_date - e_date).days,
                    "entry_z": round(float(e_z), 2),
                    "exit_z": round(float(z), 2),
                    "pnl": round(float(pnl), 2),
                    "return_pct": round(float(pnl / capital * 100), 2),
                    "result": "WIN" if pnl > 0 else "LOSS",
                    "exit_reason": reason,
                    "status": "CLOSED",
                })
                position = 0

        # mark-to-market so the equity curve is smooth even while a trade is open
        unreal = 0.0
        if position != 0:
            unreal = _trade_pnl(mode, position, e_a, e_b, a_px, b_px, capital)
            unreal -= round_trip_cost / 2       # entry cost already paid
        daily.append((date, realized + unreal))

    # if a trade is still open at the end, surface it as an OPEN row
    if position != 0:
        last_a, last_b, last_z = pa.iloc[-1], pb.iloc[-1], sp["z"].iloc[-1]
        pnl = _trade_pnl(mode, position, e_a, e_b, last_a, last_b, capital)
        pnl -= round_trip_cost / 2              # entry cost paid; exit still to come
        trades.append({
            "pair": pair["name"],
            "direction": _direction_label(mode, position, a, b),
            "entry_date": e_date.date().isoformat(),
            "exit_date": "(still open)",
            "days_held": (sp.index[-1] - e_date).days,
            "entry_z": round(float(e_z), 2),
            "exit_z": round(float(last_z), 2),
            "pnl": round(float(pnl), 2),
            "return_pct": round(float(pnl / capital * 100), 2),
            "result": "OPEN",
            "exit_reason": "open",
            "status": "OPEN",
        })

    daily_series = pd.Series(
        {d: v for d, v in daily}, name=pair["name"]
    ).astype(float)
    return trades, daily_series, sp


# ---------------------------------------------------------------------------
# 5) WATCHLIST
# ---------------------------------------------------------------------------
def watchlist_rows(close, watchlist):
    """Current ratio, z-score and the signal you'd act on right now for each watched pair."""
    rows = []
    for pair in watchlist:
        try:
            sp = compute_spread(close, pair)
            z = sp["z"].dropna().iloc[-1]
            ratio = sp["ratio"].dropna().iloc[-1]
        except (KeyError, IndexError):
            rows.append({"name": pair["name"], "ratio": None, "z": None,
                         "signal": "no data", "level": "muted"})
            continue

        ez = pair["entry_z"]
        if z >= ez:
            signal, level = f'SHORT {pair["a"]}  /  LONG {pair["b"]}', "short"
        elif z <= -ez:
            signal, level = f'LONG {pair["a"]}  /  SHORT {pair["b"]}', "long"
        elif abs(z) >= ez * 0.75:
            signal, level = "approaching entry — watch", "warn"
        else:
            signal, level = "no signal (wait)", "muted"

        rows.append({"name": pair["name"], "ratio": round(float(ratio), 4),
                     "z": round(float(z), 2), "signal": signal, "level": level})
    return rows


# ---------------------------------------------------------------------------
# 6) DASHBOARD
# ---------------------------------------------------------------------------
GREEN, RED, BLUE, AMBER, MUTED = "#16c784", "#ea3943", "#3b82f6", "#f0b90b", "#8a8f98"


def _equity_figure(combined_equity):
    fig = go.Figure()
    fig.add_trace(go.Scatter(
        x=combined_equity.index, y=combined_equity.values,
        mode="lines", line=dict(color=BLUE, width=2), name="Cumulative P&L",
        fill="tozeroy", fillcolor="rgba(59,130,246,0.12)"))
    fig.add_hline(y=0, line=dict(color=MUTED, width=1, dash="dot"))
    fig.update_layout(template="plotly_dark", height=340,
                      margin=dict(l=50, r=20, t=10, b=30),
                      paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      yaxis_title="Cumulative P&L ($)")
    return fig


def _pair_figure(close, pair, sp, trades):
    a, b = pair["a"], pair["b"]
    fig = make_subplots(rows=2, cols=1, shared_xaxes=True, vertical_spacing=0.06,
                        row_heights=[0.45, 0.55],
                        subplot_titles=(f"{a} vs {b} — normalized to 100", "Spread z-score"))

    norm_a = close[a] / close[a].dropna().iloc[0] * 100
    norm_b = close[b] / close[b].dropna().iloc[0] * 100
    fig.add_trace(go.Scatter(x=norm_a.index, y=norm_a, name=a, line=dict(color=BLUE)), 1, 1)
    fig.add_trace(go.Scatter(x=norm_b.index, y=norm_b, name=b, line=dict(color=AMBER)), 1, 1)

    fig.add_trace(go.Scatter(x=sp.index, y=sp["z"], name="z-score",
                             line=dict(color="#c9d1d9")), 2, 1)
    for lev, col in [(pair["entry_z"], RED), (-pair["entry_z"], GREEN),
                     (pair["exit_z"], MUTED), (-pair["exit_z"], MUTED)]:
        fig.add_hline(y=lev, line=dict(color=col, width=1, dash="dash"), row=2, col=1)
    fig.add_hline(y=0, line=dict(color=MUTED, width=1), row=2, col=1)

    # mark entries/exits of this pair's trades on the z-score chart
    zser = sp["z"]
    for t in trades:
        if t["pair"] != pair["name"]:
            continue
        ed = pd.Timestamp(t["entry_date"])
        if ed in zser.index:
            fig.add_trace(go.Scatter(x=[ed], y=[zser.loc[ed]], mode="markers",
                          marker=dict(symbol="triangle-up", size=11, color="#ffffff"),
                          showlegend=False, hovertext="ENTRY", name="entry"), 2, 1)
        if t["status"] == "CLOSED":
            xd = pd.Timestamp(t["exit_date"])
            if xd in zser.index:
                fig.add_trace(go.Scatter(x=[xd], y=[zser.loc[xd]], mode="markers",
                              marker=dict(symbol="x", size=10,
                                          color=GREEN if t["pnl"] > 0 else RED),
                              showlegend=False, hovertext="EXIT", name="exit"), 2, 1)

    fig.update_layout(template="plotly_dark", height=460,
                      margin=dict(l=50, r=20, t=30, b=30),
                      paper_bgcolor="rgba(0,0,0,0)", plot_bgcolor="rgba(0,0,0,0)",
                      legend=dict(orientation="h", y=1.12))
    return fig


def build_dashboard(cfg, close, extra_html=""):
    all_trades = []
    daily_list = []
    pair_figs = []

    for pair in cfg["pairs"]:
        trades, daily, sp = backtest_pair(close, pair)
        all_trades.extend(trades)
        daily_list.append(daily)
        pair_figs.append((pair, _pair_figure(close, pair, sp, trades)))

    # ----- combine per-pair equity into one curve -----
    if daily_list:
        full_idx = sorted(set().union(*[d.index for d in daily_list]))
        combined = sum(d.reindex(full_idx).ffill().fillna(0.0) for d in daily_list)
    else:
        combined = pd.Series(dtype=float)

    # ----- headline stats -----
    closed = [t for t in all_trades if t["status"] == "CLOSED"]
    wins = [t for t in closed if t["pnl"] > 0]
    realized_total = sum(t["pnl"] for t in closed)
    open_total = sum(t["pnl"] for t in all_trades if t["status"] == "OPEN")
    win_rate = (len(wins) / len(closed) * 100) if closed else 0.0
    avg_trade = (realized_total / len(closed)) if closed else 0.0
    best = max((t["pnl"] for t in closed), default=0.0)
    worst = min((t["pnl"] for t in closed), default=0.0)

    # ----- risk-adjusted metrics (more honest than win rate alone) -----
    if len(combined) > 1:
        max_dd = float((combined.cummax() - combined).max())   # worst peak-to-trough ($)
        daily_change = combined.diff().dropna()
        sd = daily_change.std()
        sharpe = float(daily_change.mean() / sd * np.sqrt(252)) if sd > 0 else 0.0
    else:
        max_dd, sharpe = 0.0, 0.0
    gross_win = sum(t["pnl"] for t in wins)
    gross_loss = abs(sum(t["pnl"] for t in closed if t["pnl"] < 0))
    profit_factor = (gross_win / gross_loss) if gross_loss > 0 else float("inf")
    pf_txt = "∞" if profit_factor == float("inf") else f"{profit_factor:.2f}"

    stats = [
        ("Realized P&L", f"${realized_total:,.0f}", GREEN if realized_total >= 0 else RED),
        ("Open P&L", f"${open_total:,.0f}", GREEN if open_total >= 0 else RED),
        ("Closed trades", f"{len(closed)}", BLUE),
        ("Win rate", f"{win_rate:.0f}%", GREEN if win_rate >= 50 else AMBER),
        ("Sharpe (daily)", f"{sharpe:.2f}", GREEN if sharpe >= 1 else AMBER if sharpe >= 0 else RED),
        ("Max drawdown", f"-${max_dd:,.0f}", RED if max_dd > 0 else MUTED),
        ("Profit factor", pf_txt, GREEN if profit_factor >= 1.5 else AMBER if profit_factor >= 1 else RED),
        ("Avg / trade", f"${avg_trade:,.0f}", MUTED),
        ("Best / Worst", f"${best:,.0f} / ${worst:,.0f}", MUTED),
    ]

    # Current-signal rows for every pair we care about. We mark which ones are
    # actually traded (in cfg["pairs"]) vs. only being watched, so the dashboard
    # can show them in two separate tables. Traded pairs are listed first, and a
    # traded pair appears even if it was left out of the "watchlist" array.
    traded_names = {p["name"] for p in cfg["pairs"]}
    seen, all_watch = set(), []
    for p in cfg["pairs"] + cfg["watchlist"]:
        if p["name"] not in seen:
            seen.add(p["name"])
            all_watch.append(p)

    wl = watchlist_rows(close, all_watch)
    for r in wl:
        r["traded"] = r["name"] in traded_names

    # save a CSV trade log too (so trades persist and can be opened in Excel)
    if all_trades:
        pd.DataFrame(all_trades).to_csv(os.path.join(DATA_DIR, "trades.csv"), index=False)

    html = _render_html(stats, wl, combined, pair_figs, all_trades, extra_html)
    out = os.path.join(HERE, "dashboard.html")
    with open(out, "w", encoding="utf-8") as f:
        f.write(html)
    return out, all_trades


def _render_html(stats, watchlist, combined, pair_figs, trades, extra_html=""):
    def fig_html(fig, i):
        return fig.to_html(full_html=False, include_plotlyjs=False, div_id=f"fig{i}")

    stat_cards = "".join(
        f'<div class="card"><div class="label">{lbl}</div>'
        f'<div class="value" style="color:{col}">{val}</div></div>'
        for lbl, val, col in stats)

    lvl_color = {"short": RED, "long": GREEN, "warn": AMBER, "muted": MUTED}

    def wl_table(rows, empty_msg):
        if not rows:
            return f'<tr><td colspan="4" style="color:#8a8f98">{empty_msg}</td></tr>'
        out = ""
        for r in rows:
            c = lvl_color.get(r["level"], MUTED)
            z = "—" if r["z"] is None else f'{r["z"]:+.2f}'
            ratio = "—" if r["ratio"] is None else f'{r["ratio"]:.4f}'
            out += (f'<tr><td class="mono">{r["name"]}</td><td class="mono">{ratio}</td>'
                    f'<td class="mono" style="color:{c}">{z}</td>'
                    f'<td style="color:{c};font-weight:600">{r["signal"]}</td></tr>')
        return out

    traded_rows = wl_table([r for r in watchlist if r.get("traded")],
                           "No traded pairs configured.")
    watch_only_rows = wl_table([r for r in watchlist if not r.get("traded")],
                               "No watch-only pairs — everything you watch is being traded.")

    tr_rows = ""
    for t in sorted(trades, key=lambda x: x["entry_date"], reverse=True):
        col = {"WIN": GREEN, "LOSS": RED, "OPEN": AMBER}[t["result"]]
        tr_rows += (
            f'<tr><td class="mono">{t["pair"]}</td><td>{t["direction"]}</td>'
            f'<td class="mono">{t["entry_date"]}</td><td class="mono">{t["exit_date"]}</td>'
            f'<td class="mono">{t["days_held"]}d</td>'
            f'<td class="mono">{t["entry_z"]:+.2f} → {t["exit_z"]:+.2f}</td>'
            f'<td class="mono" style="color:{col}">${t["pnl"]:,.0f}</td>'
            f'<td class="mono" style="color:{col}">{t["return_pct"]:+.1f}%</td>'
            f'<td style="color:{col};font-weight:600">{t["result"]}</td></tr>')
    if not tr_rows:
        tr_rows = '<tr><td colspan="9" style="color:#8a8f98">No trades generated yet.</td></tr>'

    equity_html = _equity_figure(combined).to_html(
        full_html=False, include_plotlyjs=False, div_id="equity")
    pair_blocks = "".join(
        f'<div class="panel"><h3>{p["name"]}</h3>{fig_html(f, i)}</div>'
        for i, (p, f) in enumerate(pair_figs))

    now = dt.datetime.now().strftime("%Y-%m-%d %H:%M:%S")
    return f"""<!DOCTYPE html><html><head><meta charset="utf-8">
<title>Pair-Trading Dashboard</title>
<script src="https://cdn.plot.ly/plotly-2.35.2.min.js"></script>
<style>
  body{{background:#0d1117;color:#e6edf3;font-family:-apple-system,Segoe UI,Roboto,sans-serif;margin:0;padding:24px}}
  h1{{margin:0 0 4px}} h2{{margin:28px 0 12px;font-size:18px;border-left:3px solid {BLUE};padding-left:10px}}
  h3{{margin:0 0 8px;font-size:15px;color:#c9d1d9}}
  .sub{{color:#8a8f98;font-size:13px;margin-bottom:18px}}
  .mono{{font-family:ui-monospace,Consolas,monospace}}
  .cards{{display:flex;gap:12px;flex-wrap:wrap}}
  .card{{background:#161b22;border:1px solid #21262d;border-radius:10px;padding:14px 18px;min-width:130px}}
  .card .label{{color:#8a8f98;font-size:12px}} .card .value{{font-size:22px;font-weight:700;margin-top:4px}}
  .panel{{background:#161b22;border:1px solid #21262d;border-radius:10px;padding:16px;margin-bottom:16px}}
  table{{width:100%;border-collapse:collapse;font-size:13px}}
  th,td{{text-align:left;padding:8px 10px;border-bottom:1px solid #21262d}}
  th{{color:#8a8f98;font-weight:600;font-size:12px;text-transform:uppercase;letter-spacing:.04em}}
  tr:hover td{{background:#1c2230}}
  .note{{background:#1a1f2b;border:1px solid #2a3344;border-radius:8px;padding:10px 14px;color:#9aa4b2;font-size:12px;margin-top:24px}}
</style></head><body>
  <h1>Pair-Trading Dashboard</h1>
  <div class="sub">Generated {now} &nbsp;·&nbsp; backtested signals &amp; simulated trades (no real money)</div>

  <h2>Summary</h2>
  <div class="cards">{stat_cards}</div>

  <h2>Traded pairs — live signal</h2>
  <div class="sub">The pairs in your <span class="mono">pairs</span> list. These are backtested and charted below.</div>
  <div class="panel"><table>
    <tr><th>Pair</th><th>Ratio</th><th>z-score</th><th>Signal</th></tr>
    {traded_rows}
  </table></div>

  <h2>Watchlist only — watching, not trading</h2>
  <div class="sub">Candidates you're monitoring. Move one into the <span class="mono">pairs</span> list in pairs.json to start trading it.</div>
  <div class="panel"><table>
    <tr><th>Pair</th><th>Ratio</th><th>z-score</th><th>Signal</th></tr>
    {watch_only_rows}
  </table></div>

  <h2>Equity curve</h2>
  <div class="panel">{equity_html}</div>

  <h2>Per-pair detail</h2>
  {pair_blocks}

  <h2>Completed trades</h2>
  <div class="panel"><table>
    <tr><th>Pair</th><th>Direction</th><th>Entry</th><th>Exit</th><th>Held</th>
        <th>z entry→exit</th><th>P&amp;L</th><th>Return</th><th>Result</th></tr>
    {tr_rows}
  </table></div>

  {extra_html}

  <div class="note">This is a research/backtest tool. Simulated results are NOT a promise of
  real returns. Pair trading involves real risk of loss. Nothing here is financial advice.</div>
</body></html>"""
